### ISSUE TITLE
[FEATURE] Add option to change labels (or use locale)

### ISSUE THREAD

**Issue by jmazier-j2d** [WebsiteBeaver/react-native-document-scanner-plugin#1]
Hello ! 

First of all, thank you very much for this package, it's awesome !

I'm looking to change the labels or apply a locale (french, english, ...) but couldn't find any options related to that.

I know it's still WIP, is this already planned on the roadmap ?

**Comment by dmarcs** [comment]
@jmazier-j2d you can change the app locale.

![image](https://user-images.githubusercontent.com/26162804/185708367-bda1db44-c2ae-44f0-b175-a51c235f9f7c.png)
