### ISSUE TITLE
[Unhandled promise rejection: Error: The package 'react-native-document-scanner-plugin' doesn't seem to be linked. Make sure:

### ISSUE THREAD

**Issue by shahidavalisyed** [WebsiteBeaver/react-native-document-scanner-plugin#100]
[Unhandled promise rejection: Error: The package 'react-native-document-scanner-plugin' doesn't seem to be linked. Make sure: ]
at node_modules\react-native-document-scanner-plugin\src\index.tsx:null in <global>
at node_modules\react-native-document-scanner-plugin\src\index.tsx:null in <global>
at http://19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false&strict=false&minify=false:null in ?anon_0_      
at node_modules\@babel\runtime\helpers\asyncToGenerator.js:null in asyncGeneratorStep
at node_modules\@babel\runtime\helpers\asyncToGenerator.js:null in _throw
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:null in queueReactNativeMicrotask
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:null in _callTimer
- ... 8 more stack frames from framework internals

**Comment by dmarcs** [comment]
If you're using an emulator try switching to a physical device.
