### ISSUE TITLE
Apk and AAB Size Increases by 50%

### ISSUE THREAD

**Issue by MirFahad58** [WebsiteBeaver/react-native-document-scanner-plugin#106]
Issue Description:

**Problem**
The size of the generated APK (Android Package) and AAB (Android App Bundle) has increased significantly by approximately 50% when using the react-native-document-scanner-plugin in our React Native project.

**Steps to Reproduce**
Install the latest version of the react-native-document-scanner-plugin.
Integrate it into a React Native project.
Build the project for Android.
Observe the increase in the size of the generated APK and AAB.
Expected Behavior
The size of the APK and AAB should remain relatively stable or increase only marginally with the addition of the react-native-document-scanner-plugin.

**Actual Behavior**
The size of the APK and AAB has increased by approximately 50%, which is unexpected and could significantly impact the performance and user experience of the application.

**Environment**
React Native version:  0.63.4 and 0.68.0
react-native-document-scanner-plugin version:  latest

**Additional Information**
Any additional information or context that might help in resolving this issue. For example, are there specific configurations or settings that can be adjusted to mitigate the increase in size?

**Comment by shawkifitouri1** [comment]
did you figure out any solution please ?

**Comment by MirFahad58** [comment]
@shawkifitouri1 no, i think we can not reduce because it uses open-cv sdk

**Comment by eladgel** [comment]
What is the size difference

**Comment by dmarcs** [comment]
fixed in 1.0.0 https://github.com/WebsiteBeaver/react-native-document-scanner-plugin/pull/113 (switch to built-in Android document scanner)
