### ISSUE TITLE
REMOVE AUTO CROPPING / DISABLE DOCUMENT BORDER DETECTION

### ISSUE THREAD

**Issue by jujupec** [WebsiteBeaver/react-native-document-scanner-plugin#110]
When we take a photo with the module, it detects the document and automatically crops the photo. Would it be possible to disable this but still keep the ability to crop the photo afterwards?

**Comment by dmarcs** [comment]
duplicate of https://github.com/WebsiteBeaver/react-native-document-scanner-plugin/issues/45

**Comment by skyllex94** [comment]
Any update on this, if we can have it as an option in the properties of DocumentScanner.scanDocument() that would be amazing!
