### ISSUE TITLE
ImageUtil.getImageMatrixFromFilePath  ava.lang.NullPointerException - Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference

### ISSUE THREAD

**Issue by Nadimkhan120** [WebsiteBeaver/react-native-document-scanner-plugin#112]
This issue is coming on Google play store on android 
 fileName ImageUtil.kt:68
<img width="1212" alt="Screenshot 2024-01-15 at 9 33 16 PM" src="https://github.com/WebsiteBeaver/react-native-document-scanner-plugin/assets/93160686/7d224f57-8928-48c9-981c-f5b7c3fe53d0">
<img width="1184" alt="Screenshot 2024-01-15 at 9 33 39 PM" src="https://github.com/WebsiteBeaver/react-native-document-scanner-plugin/assets/93160686/37fd60ad-8ba8-44bf-9048-2a0a9214d60a">

**Comment by Nadimkhan120** [comment]
@dmarcs can you please look into this as our app in production, it will be very grateful if you help on this.

**Comment by oalsc** [comment]
same issue here

**Comment by VasylenckoSlava** [comment]
same issue here

**Comment by dmarcs** [comment]
fixed in 1.0.0 https://github.com/WebsiteBeaver/react-native-document-scanner-plugin/pull/113 (switch to built-in Android document scanner)
