### ISSUE TITLE
Enhancement Request - The ability to define pre-set camera settings

### ISSUE THREAD

**Issue by msouheib** [WebsiteBeaver/react-native-document-scanner-plugin#117]
It would be very helpful if we could pre-set the camera settings (Manual instead of auto and Grayscale instead of color) so that they don't have to be changed on every scan.

**Comment by dmarcs** [comment]
Good idea, but this is a duplicate https://github.com/WebsiteBeaver/react-native-document-scanner-plugin/issues/79
