### ISSUE TITLE
react-native-document-scanner-plugin:verifyReleaseResources

### ISSUE THREAD

**Issue by Hassan-jr** [WebsiteBeaver/react-native-document-scanner-plugin#12]
Can someone tell me how to resolve this error

``` Execution failed for task ':react-native-document-scanner-plugin:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:C:\Users\Abdiladif Hassan\.gradle\caches\transforms-3\b2197c574567c595cb9e45a5d8e1862d\transformed\core-1.7.0\res\values\values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found. ```

**Comment by dmarcs** [comment]
How do we know this plugin is causing that error? Maybe another plugin is causing it.

**Comment by Hassan-jr** [comment]
dmarc it was this plugin that was causing the error.
I solved the error by.
 *Changing the minimum and maximum SDK versions specified in the plugin*

**Comment by dmarcs** [comment]
Thanks for sharing the solution

**Comment by nicolascavallin** [comment]
+1 thanks for the solution, @Hassan-jr.

**Comment by hasansajora** [comment]
I am also facing this error while generating release-apk.
so is there any plan to integrate this change?
