### ISSUE TITLE
Add ability to detect if the device supports the document scanner?

### ISSUE THREAD

**Issue by humphreyja** [WebsiteBeaver/react-native-document-scanner-plugin#128]
This would be nice for older android devices that do not have the document scanner available through play services and things like that. 

Maybe a hook?

```js
const ScanDocs = () => {
  const { supportsScanning } = useDocumentScannerConfig();
  if (!supportsScanning) return null;
   

  // ... button to otherwise launch the scanner
}
```

I could probably throw together a PR for you here, just wanted to make sure something like this wasn't already implemented.

**Comment by dmarcs** [comment]
That is a good idea, but at the same time I want to keep the code as simple as possible.
