### ISSUE TITLE
Document scanning is not supported on this device promiseMethodWrapper

### ISSUE THREAD

**Issue by ClickMakers** [WebsiteBeaver/react-native-document-scanner-plugin#13]
working well on android but on ios it shows me this message

Document scanning is not supported on this device
promiseMethodWrapper

and on real devices screen open for just 1 second and after that autoclose

Uploading IMG_4457 (online-video-cutter.com).mp4… 

whats the problem on ios i don't know

**Comment by dmarcs** [comment]
you need to use iOS 13 or above

**Comment by ClickMakers** [comment]
okay thanks

**Comment by ClickMakers** [comment]
https://user-images.githubusercontent.com/89856868/197418132-5b68695c-7883-4a71-94fe-37a8afa96e60.mp4


this is the main issue, open scanner and close automatically
