### ISSUE TITLE
scanner opened and close within 1 second 

### ISSUE THREAD

**Issue by ClickMakers** [WebsiteBeaver/react-native-document-scanner-plugin#14]
https://user-images.githubusercontent.com/89856868/197615600-470b8109-aca1-4fce-ab40-21afa821a70a.mp4

this is real device and the ios version is greater than 13 but I received this issue

**Comment by dmarcs** [comment]
Maybe you didn't add a usage description to Info.plist

**Comment by ClickMakers** [comment]
<key>NSCameraUsageDescription</key>
<string>To capture the photo user wants to upload</string>

This is description in  Info.plist

**Comment by ClickMakers** [comment]
its working now but close app after some clicks and showing this issue App terminated due to memory issue

**Comment by dmarcs** [comment]
Maybe that's caused by another plugin. I would need more proof that this plugin is causing your app to crash.
