### ISSUE TITLE
Auto Object Detection not happening and cropped image is not at exact

### ISSUE THREAD

**Issue by ibhushanlunkad** [WebsiteBeaver/react-native-document-scanner-plugin#15]
**Issue 1.** When we open camera and scan for document, it allows to take picture but it does not auto detect the object/ document i.e 4 corners of the document. After taking picture on click of OK, it shows the preview of the image with 4 corners and allows to adjust the image.

**Issue 2**. When we adjust the image and submit, the submitted image is cropped more than what we selected and the image is blurred.

**Comment by dmarcs** [comment]
Auto detect on Android isn't available as of now. Please add a video that shows issue 2.

**Comment by ibhushanlunkad** [comment]
https://user-images.githubusercontent.com/60914754/199664332-30d5e78d-26ab-498b-bdff-44b865cc89f8.mp4

Please check the attached video. See the cropped points and see the image, how it has been cropped.

Questions: 
- When can we expect Auto detect for Android? 
- Are we using OpenCV for iOS?

**Comment by maimistery** [comment]
The same thing happens to me as issue 2

**Comment by dmarcs** [comment]
Try

```
<Image
  resizeMode="contain"
  style={{ width: '100%', height: '100%' }}
  source={{ uri: scannedImage }}
/>
```

or

```
<Image
  style={{ width: '100%', height: '100%', object-fit: contain }}
  source={{ uri: scannedImage }}
/>
```

Auto detect will probably be available once Android adds a native document scanner sdk.
