### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by bvanheukelom** [WebsiteBeaver/react-native-document-scanner-plugin#17]
Could you point me to an example or guides that show how this fine library can be used in different languages (german etc) ?

**Comment by dmarcs** [comment]
You can change the iOS project language to make it work in any locale you want. The Android version doesn't have words.

**Comment by bvanheukelom** [comment]
Thank you for the quick response!

Just to clarify (not a full time mobile dev here) : Will the scanner also change its language if the user changes the language on their phone?

**Comment by majirosstefan** [comment]
We should have the ability to set props labels (as props) - please, consider reopening this

**Comment by bjarnewilhelm** [comment]
Would be extremely helpful if we could have localization. As we need to have 4 languages in our app to support different user groups this would make life a lot easier for us. @dmarcs please consider reopening this issue.
