### ISSUE TITLE
Cannot find module './expo-plugin/build/withDocumentScanner'

### ISSUE THREAD

**Issue by eduardfarkas** [WebsiteBeaver/react-native-document-scanner-plugin#19]
I wanted to try this library so I upgraded my project to expo sdk 47. But the plugin cannot be found.
I see it in the node-modules, but expo does not.

error:
-----
CommandError: Cannot find module './expo-plugin/build/withDocumentScanner'
Require stack:
- /Users/edfarkas/Projects/nathan-scanner/node_modules/react-native-document-scanner-plugin/app.plugin.js
- /Users/edfarkas/Projects/nathan-scanner/node_modules/@expo/config-plugins/build/utils/plugin-resolver.js
- /Users/edfarkas/Projects/nathan-scanner/node_modules/@expo/config-plugins/build/plugins/withStaticPlugin.js
- /Users/edfarkas/Projects/nathan-scanner/node_modules/@expo/config-plugins/build/plugins/withPlugins.js
- /Users/edfarkas/Projects/nathan-scanner/node_modules/@expo/config-plugins/build/index.js
- /Users/edfarkas/Projects/nathan-scanner/node_modules/@expo/cli/build/src/prebuild/clearNativeFolder.js
- /Users/edfarkas/Projects/nathan-scanner/node_modules/@expo/cli/build/src/prebuild/prebuildAsync.js
- /Users/edfarkas/Projects/nathan-scanner/node_modules/@expo/cli/build/src/prebuild/index.js
- /Users/edfarkas/Projects/nathan-scanner/node_modules/@expo/cli/build/bin/cli

**Comment by dmarcs** [comment]
fixed in https://github.com/WebsiteBeaver/react-native-document-scanner-plugin/commits/0.2.1 by running build in pipeline
