### ISSUE TITLE
[FEATURE] Skip the multipage option

### ISSUE THREAD

**Issue by jmazier-j2d** [WebsiteBeaver/react-native-document-scanner-plugin#2]
Hello again,

I'm looking for a way to skip the multipage option, in other words, I would like the scanner to return (if option is set to true) as soon as the first scan is done.

I will look deeper in your code and might just fork the project in order to add this feature, but you might be already working on something similar, so I'd better ask first :)

Thank you again for the huge work and for sharing with the community !

**Comment by dmarcs** [comment]
Yes you can by setting **maxNumDocuments** to 1. Right now this only works on Android

**Comment by jmazier-j2d** [comment]
Thanks @dmarcs, did not think I could use this option that way. That will be better than nothing for now 👍

**Comment by dmarcs** [comment]
This issue will be fixed once #5 is fixed
