### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by eduardfarkas** [WebsiteBeaver/react-native-document-scanner-plugin#20]
Would it be possible to customize button texts to different language?
I tried to look through the code but wasnt able to find where it was defined (ios).

**Comment by eduardfarkas** [comment]
hi David,
thank you for advice. I was able to change language to czech, which will be the main language.
However maybe i phrased my question wrongly. I would like to switch the language at runtime as my app should be multilingual. Would this be somehow possible to do?

**Comment by psalkowski** [comment]
hi @dmarcs , I just installed the plugin and it looks awesome so far! 

But we have similar issue as @eduardfarkas. Our application is multi language app, and user can change language at runtime.
