### ISSUE TITLE
 "RNPdfScanner" was not found in the UIManager.

### ISSUE THREAD

**Issue by TanKucukhas** [WebsiteBeaver/react-native-document-scanner-plugin#21]
I am trying to run this on is using the following config
    "react": "18.1.0",
    "react-native": "0.70.4",
    "react-native-document-scanner-plugin": "^0.2.1",
    
And i am getting following error:
Invariant Violation: requireNativeComponent: "RNPdfScanner" was not found in the UIManager.

**Comment by anhdo9797** [comment]
I same issue, please give me your solution 
Thanks
