### ISSUE TITLE
Shows black screen while cropping on android 8 only

### ISSUE THREAD

**Issue by mashad6** [WebsiteBeaver/react-native-document-scanner-plugin#23]
Uploading WhatsApp Video 2022-11-17 at 6.14.57 PM.mp4…

![WhatsApp Image 2022-11-17 at 6 13 46 PM](https://user-images.githubusercontent.com/55269021/202456291-ad307f99-bfdc-469b-a062-d9fae8ce9462.jpeg)

**Comment by dmarcs** [comment]
Can you try with a newer Android version?

**Comment by mashad6** [comment]
@dmarcs works fine on new versions, but not on android 8.

**Comment by mashad6** [comment]
android 8 and fewer version having the same issue

**Comment by mashad6** [comment]
@dmarcs are you guys going to resolve this anytime soon?

**Comment by dmarcs** [comment]
I wasn't able to reproduce this bug on an emulator using Android 8. I'm not sure why this happens. Maybe the image is too big, and the phone runs out of memory.

**Comment by mashad6** [comment]
@dmarcs try running on a physical device and use your rear camera. it'll reproduce

**Comment by dmarcs** [comment]
My physical device has Android 12. It doesn't seem easy to downgrade.
