### ISSUE TITLE
[BUG] Android base64 generating text 'file://' infront of b64 data

### ISSUE THREAD

**Issue by eduardfarkas** [WebsiteBeaver/react-native-document-scanner-plugin#24]
When generating B64 data for image, if using android, data start with text 'file://'.

**Comment by mashad6** [comment]
const { scannedImages } = await DocumentScanner.scanDocument(
            {
                responseType: `'base64`
            }
        )

**Comment by mashad6** [comment]
`const { scannedImages } = await DocumentScanner.scanDocument(
            {
                responseType: 'base64',
                maxNumDocuments:1
            }
        )`

this will return you base64

**Comment by dmarcs** [comment]
fixed in https://github.com/WebsiteBeaver/react-native-document-scanner-plugin/tree/0.3.0

https://github.com/WebsiteBeaver/react-native-document-scanner-plugin/pull/27 remove `file://` from response
