### ISSUE TITLE
Can't upload image to firebase cloud storage on iOS

### ISSUE THREAD

**Issue by silencie** [WebsiteBeaver/react-native-document-scanner-plugin#28]
I'm using  Expo(managed workflow) I tried to upload image file after scanning the document to firebase cloud storage. 

it works fine on android but I got an error on iOS.

**on android device** :  the file path that return after scanning was like this

<img width="1009" alt="Screenshot 2565-11-20 at 21 00 25" src="https://user-images.githubusercontent.com/115603511/202909209-e37d5277-dfc3-4943-a033-343641fc9fa4.png">

**on iOS device** :  the file path was like this

<img width="1010" alt="Screenshot 2565-11-20 at 21 04 03" src="https://user-images.githubusercontent.com/115603511/202909244-e52f9aeb-1451-4e68-aff1-29dafd976e0f.png">

there is no problem on rendering the image on the screen 

    <Image
      resizeMode="contain"
      style={{ width: '100%', height: '100%' }}
      source={{ uri: scannedImage }}
    />

but when I tried to upload the image to firebase storage on iOS device i got an error.

![IMG_3551](https://user-images.githubusercontent.com/115603511/202909553-369af4bf-4615-4c84-883f-0918a25556dc.jpeg)

I noticed that the file path that return from "expo-image-picker" library was a bit different 

<img width="1171" alt="Screenshot 2565-11-20 at 21 08 18" src="https://user-images.githubusercontent.com/115603511/202909232-86a427f0-19e4-4771-bf22-3f2276fe8ab9.png">

with this uri I can upload the image with no problem.

so, does file path matter when uploading the image ? 

I'm a big fan of this repo I'm trying to figure out a way to make this work.

**Comment by dmarcs** [comment]
What does the file path on iOS look like for expo-image-picker?

**Comment by dmarcs** [comment]
You could add file:// to the file path to make it work for now. I'll see if I can have the plugin return the file path in that format.

**Comment by silencie** [comment]
> You could add file:// to the file path to make it work for now. I'll see if I can have the plugin return the file path in that format.

I have tried that but it doesn't seem to work. May be it's not about the file path.

I did some research and found that If any object is nil, there will be a crash. 

ref : [https://www.programmersought.com/article/84335994306/](url)

Could you please check the condition of every object should not be nil

**Comment by dmarcs** [comment]
show me an example where nil gets returned as the file path

**Comment by dmarcs** [comment]
I updated the iOS code to return file paths for cropped images that start with file:/// in https://github.com/WebsiteBeaver/react-native-document-scanner-plugin/tree/0.5.0.

I don't think this fixes the problem you're having, but that issue is likely unrelated to this plugin. I would check to make sure that you're using the Firebase Storage plugin correctly.
