### ISSUE TITLE
Not getting crop border detection on Android 10

### ISSUE THREAD

**Issue by ibhushanlunkad** [WebsiteBeaver/react-native-document-scanner-plugin#31]
Hi, 
It's indeed a great library for document scan. Thanks.
I am facing below issues, please have a look.
Issue 1: I am not getting Crop borders on Android 10, but it is working fine on Android 12.
Issue 2: I have observed in Android 10/12, sometimes it doesn't take to crop image and directly open up the camera. 

I am attaching a video for reference where it addresses both the issues. Awaiting for your reply.

Thanks!

https://user-images.githubusercontent.com/60914754/203120389-4f6cc405-3d24-43b5-87af-219b68c2c2a7.mp4

**Comment by dmarcs** [comment]
My guess is that the app crashes and restarts. That's probably why it opens the camera immediately after you accept the photo. I would need to see error logs since I can't reproduce the issue.

**Comment by ibhushanlunkad** [comment]
If tried multiple times that time App crashes, otherwise sometimes for Android 12  also I am facing the same issue.
