### ISSUE TITLE
Crop border detection does not detect document corners on Android

### ISSUE THREAD

**Issue by silencie** [WebsiteBeaver/react-native-document-scanner-plugin#32]
iOS is working fine.  On Android the border is showing but it does not detect document corners.
Expo + EAS build
Device : One Plus 7T Android 11

**Android**

https://user-images.githubusercontent.com/115603511/204316059-f5436a5c-2c4a-4262-a9f3-7ca1ceb8e556.mp4

**iOS**

https://user-images.githubusercontent.com/115603511/204316124-7da46503-cf97-4add-9359-461d028329a5.mp4

**Comment by dmarcs** [comment]
It's tricky since you're scanning something white on a white background.

**Comment by silencie** [comment]
> It's tricky since you're scanning something white on a white background.

I test on a dark background and it's working.
