### ISSUE TITLE
Build in Permissions Request for Camera (Android)

### ISSUE THREAD

**Issue by brennansaul** [WebsiteBeaver/react-native-document-scanner-plugin#33]
There is no built in permissions request for android resulting in the following error when initially calling 
`await DocumentScanner.scanDocument()`:

```
[Error: error - error opening camera: Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.android.camera2/com.android.camera.CaptureActivity clip={text/uri-list hasLabel(0) {U(content)}} (has extras) } from ProcessRecord{b67d90f 11508:com.dear.app.android/u0a147} (pid=11508, uid=10147) with revoked permission android.permission.CAMERA]
```

The above can be resolved with the following logic low added inside the `scanDocument` function:
- Check if camera permission has previously been granted.
- If yes, continue to scan.
- If no: 
  - Request camera permission.
  - If user approved permission, continue to scan.
  - If permission not granted, skip scan.

The above flow could be implemented using the code similar to this [example](https://developer.android.com/training/permissions/requesting#java) from android documentation. 

Alternatively we can add the permissions request at the javascript level by modifying the `index.ts` file with something like:

```
/**
 * Only used for android.
 */
const checkCameraPermission = async () => {
  try {
    if (Platform.OS === 'ios') {
      return true;
    }

    var hasCameraPermission = await PermissionsAndroid.check(
      PermissionsAndroid.PERMISSIONS.CAMERA
    );

    if (!hasCameraPermission) {
      const granted = await PermissionsAndroid.request(
        PermissionsAndroid.PERMISSIONS.CAMERA,
        {
          title: 'Requests Camera Permission',
          message: 'This functionality requires access to your camera.',
          buttonNeutral: 'Ask Me Later',
          buttonNegative: 'Cancel',
          buttonPositive: 'OK',
        }
      );
      if (granted === PermissionsAndroid.RESULTS.GRANTED) {
        return true;
      } else {
        return false;
      }
    } else {
      return true;
    }
  } catch (err) {
    return false;
  }
};

export default {
  /**
   * Opens the camera, and starts the document scan
   */
  scanDocument(
    options: ScanDocumentOptions = {}
  ): Promise<ScanDocumentResponse> {
    return checkCameraPermission()
      .then((hasCameraPermission) => {
        if (!hasCameraPermission) {
          return [Promise.resolve([])]; // return empty array
        } else {
          return DocumentScanner.scanDocument(options);
        }
      })
      .catch(() => {
        return Promise.resolve([]);
      });
  },
};
```

Is this a desired functionality for the `react-native-document-scanner-plugin`? If so I'm more than happy to contribute by submitting a PR.

**Comment by dmarcs** [comment]
This plugin works for me without prompting for `android.permission.CAMERA`. I wonder if you have another plugin installed that causes this behavior.

**Comment by brennansaul** [comment]
When I originally integrated the library this error didn't happen but when I created a new emulator for additional testing and installed the app for the first time this issue occurred. Is it possible that this issue is not happening for you because in prior development the permission was granted on your device? I believe it is this plugin causing the permission issue because the error was being displayed in the console whenever i was explicitly triggering the `await DocumentScanner.scanDocument()` function.

**Comment by dmarcs** [comment]
I've been deleting and re-creating apps without needing to ask for camera permission.

https://developer.android.com/guide/topics/media/camera The docs say that I don't need to ask for permission.
![image](https://user-images.githubusercontent.com/26162804/204703067-32c1f304-063e-444e-8887-9327045bbfc0.png)

I bet you have another plugin that specifies
`<uses-permission android:name="android.permission.CAMERA" />`
in the manifest, and that's what causes this plugin to need camera permissions to be granted by the user. Even though the error gets triggered by calling `scanDocument`, I don't think it's caused by this plugin.

If I'm right about this then users who use this plugin, and don't use another camera plugin won't have any problems. Programmers who use this plugin with another camera plugin will have the issue, but they can solve it by prompting the user for camera permissions.

**Comment by brennansaul** [comment]
@dmarcs Thank you for following up! You are right that is definitely the issue as I am using the `expo-image-picker` package` which requires `<uses-permission android:name="android.permission.CAMERA" />`. If it would be helpful, I will create a documentation PR and add these details to the project [README.md](https://github.com/WebsiteBeaver/react-native-document-scanner-plugin#readme) with and an example for implementing the android camera permissions request.

**Comment by dmarcs** [comment]
I agree that it should be part of the README. I'll add it, so you don't need to worry about creating a pull request

**Comment by brennansaul** [comment]
Ive got some time and would like to take a stab at it if you would like to review and revise!

**Comment by dmarcs** [comment]
okay thanks go ahead
