### ISSUE TITLE
app crash after taking picture 

### ISSUE THREAD

**Issue by tayyabrajpoot12** [WebsiteBeaver/react-native-document-scanner-plugin#37]
I am trying to scan document when i tried to scan it gave me a error of "unfortunatly app has stopped" after press on capture button and app exit ultimately

**Comment by dmarcs** [comment]
What error message shows up in Android Studio?

**Comment by tayyabrajpoot12** [comment]
> What error message shows up in Android Studio?

I am testing this on my android phone its version is 6.0.1 and it shows me the below message when i click on 
the ok button after crop the image functionality
 
![WhatsApp Image 2022-12-05 at 13 07 20](https://user-images.githubusercontent.com/92966044/205585964-8287f649-28e1-4bd8-b1da-5dcc848c302a.jpeg) 

and app has crashed

**Comment by dmarcs** [comment]
You have to open Android Studio and check error logs while the crash happens in order to get a more detailed error message. That error message is too generic to be able to debug.
