### ISSUE TITLE
React Native 0.70.1 on IOS 16 Scanner close itself

### ISSUE THREAD

**Issue by dror-laguna** [WebsiteBeaver/react-native-document-scanner-plugin#42]
Hi, 
first, let me say that we love your lib!!! ❤️ 
we can't figure out what the issue is there are no logs (in js), or extra data just this video:

the code is super simple 
`    console.log('BEFORE!!!!!!'); //gets called`
`    const { scannedImages } = await DocumentScanner.scanDocument();`
`    console.log('AFTER!!!!');  //doesn't gets called`
 
we added try catch but no error gets thrown
we do have camera permissions
it worked once but it doesn't anymore

https://user-images.githubusercontent.com/81741523/207322587-7320db22-baa5-4496-9839-7fadd7a170ee.MP4

any suggestion on how to proceed?

**Comment by dmarcs** [comment]
That usually happens when you don't add camera permissions

![image](https://user-images.githubusercontent.com/26162804/207345414-2c6877a7-9919-4af0-9169-a0b8fad9d521.png)

**Comment by dror-laguna** [comment]
we do have access...

**Comment by dror-laguna** [comment]
here it the log  from xcode 2022-12-13 15:57:08.704911+0200 Laguna[2343:737625] Unbalanced calls to begin/end appearance transitions for <RCTModalHostViewController: 0x11568fd40>.
