### ISSUE TITLE
croppedImageQuality not working on Android

### ISSUE THREAD

**Issue by Lump01** [WebsiteBeaver/react-native-document-scanner-plugin#43]
I have a util that tells me the length of the base64 string of an image and it is the same before and after I added the croppedImageQuality in Android.

**Comment by dmarcs** [comment]
Maybe you're using an older version of this plugin that doesn't support croppedImageQuality

**Comment by Lump01** [comment]
I had run an npm install and update but it was an issue where I had to restart metro server I think.
