### ISSUE TITLE
iOS: Limit of images

### ISSUE THREAD

**Issue by RJosue** [WebsiteBeaver/react-native-document-scanner-plugin#5]
Hi 👋🏽, thanks for this lib.🎉
Is possible have a prop to limit the amount of images for iOS, like in android?

**Comment by dmarcs** [comment]
Right now it's not. I'm hoping that iOS allows that to be a configuration in the future.

**Comment by udaysagartammina** [comment]
Hi, is there any possible to skip the multipage option.
thanks in advance.

**Comment by juliusoh** [comment]
why cant ios be limited to 1?
