### ISSUE TITLE
With the expo it's not working

### ISSUE THREAD

**Issue by Relison** [WebsiteBeaver/react-native-document-scanner-plugin#53]
Erro: The package 'react-native-document-scanner-plugin' doesnt seem to be linked. Make sure:

- You rebuilt the app after installing the package
- you are not using Expo managed workflow

Obrigado!

**Comment by dmarcs** [comment]
See https://github.com/WebsiteBeaver/react-native-document-scanner-plugin/discussions/51. Someone else is having the same issue.

I just tested the plugin using Expo, and it works for me.

```
npx create-expo-app my-app
npx expo install react-native-document-scanner-plugin
npx expo prebuild
npm run android
```

Did you create the project using `npx create-expo-app my-app`?

**Comment by Relison** [comment]
Thanks for the feedback!

Yes using "npx create-expo-app my-app"

package.json
"dependencies": {
    "expo": "~47.0.12",
    "react": "18.1.0",
    "react-dom": "18.1.0",
    "react-native": "0.70.5",
    "react-native-document-scanner-plugin": "^0.7.1",
    "react-native-web": "~0.18.9",
    "sharp-cli": "^2.1.0"
  },

**Comment by dmarcs** [comment]
why is expo-status-bar missing from your package.json?

**Comment by Relison** [comment]
The problem is the execution of the Emulator, I sent it to the Google store and it worked perfectly.

I was emulating inside the android expo

Thanks! For the return!

**Comment by nazirahmad7340** [comment]
@dmarcs 
The react-native-document-scanner-plugin is not working with ios please check once. For Android it's ok. 
I tested with different states but always showed the below error. 

Erro: The package 'react-native-document-scanner-plugin' doesnt seem to be linked. Make sure:
You rebuilt the app after installing the package
you are not using Expo managed workflow
......

**Comment by jaya-shankar** [comment]
+1
