### ISSUE TITLE
 Remove junk files after scanning

### ISSUE THREAD

**Issue by hm1061998** [WebsiteBeaver/react-native-document-scanner-plugin#54]
I want to remove the image files stored on the client side after use. is there any way?

**Comment by dmarcs** [comment]
You can use a React Native plugin that lets you delete files.

**Comment by maimistery** [comment]
For example you can use the plugin  react-native-fs

_var RNFS = require('react-native-fs');

...

await RNFS.exists(filepath).then((exists) => {
  if (exists) {
      RNFS.unlink(filepath).then(() => {
         RNFS.scanFile(filepath);
      })
   }
});_

**Comment by hm1061998** [comment]
i am using expo-file-system library, 
when I call:
```
 await FileSystem.deleteAsync(path, {
            intermediates: true,
          });
```
I get an error like this:
 [Error: Location 'file:///storage/emulated/0/Android/data/dev.com.vgasoft.lawyerpro/files/Pictures/DOCUMENT_SCAN_0_20230131_1545188951033221565856033.jpg' isn't deletable.]

**Comment by maimistery** [comment]
Sorry , with expo I can't help you , here is the same error:https://github.com/expo/expo/issues/2996
