### ISSUE TITLE
How are images stored?

### ISSUE THREAD

**Issue by eduardfarkas** [WebsiteBeaver/react-native-document-scanner-plugin#56]
Hi,
I would like to ask about storing images.
If I take jpg picture, is it cached or stored somewhere permanently?

What are the ways to manage this? Should i delete those pictures manually?

Thanks in advence

**Comment by dmarcs** [comment]
Images are stored as files on Android and iOS. If a user deletes the app, the files get deleted. 

You can store them somewhere else like S3 if you want, and you can delete them manually.

**Comment by eduardfarkas** [comment]
@dmarcs i would like to delete scans that i have processed, but with expo filesystem i cannot do it.
How do I delete scans that I no longer need? I don't want to bloat memory with unneccessary images.

**Comment by hm1061998** [comment]
> @dmarcs i would like to delete scans that i have processed, but with expo filesystem i cannot do it. How do I delete scans that I no longer need? I don't want to bloat memory with unneccessary images.

I also have the same problem, the image files after scanning are not automatically deleted causing the memory to be full.
using expo-file-system cannot delete them.
have you solved it yet?

**Comment by eduardfarkas** [comment]
@hm1061998 not really, i saw that expo-media-library should do the trick because it can access camera roll folder (i didnt try it yet), but the path to the file is in the scope of the app if i understand it right, so expo-file-system should work.
Anyway, for now I am waiting for @dmarcs to answer it.

(and i hope there is a way to delete it, otherwise i dont know what will i do :D)

**Comment by dmarcs** [comment]
@hm1061998 @eduardfarkas can't you use https://docs.expo.dev/versions/latest/sdk/filesystem to delete the files?

**Comment by eduardfarkas** [comment]
It says that the file is not deletable. I have tried to modify the path a little bit just in case it was wrong but i had no success.
I would like to ask you to try to reproduce it on your end. I tried it on android simulator on macos.

**Comment by dmarcs** [comment]
I was able to delete files using https://www.npmjs.com/package/react-native-fs.

**Comment by eduardfarkas** [comment]
sorry for delay, i tried this library https://github.com/DylanVann/react-native-fast-image and i was also able to delete the image.
I suggest putting this information in the readme so other users will be aware that images must be deleted with external library.
btw, thank you for trying it yourself

**Comment by silencie** [comment]
> @dmarcs sorry for delay, i tried this library https://github.com/DylanVann/react-native-fast-image and i was also able to delete the image. I suggest putting this information in the readme so other users will be aware that images must be deleted with external library. btw, thank you for trying it yourself

How did you do that ? Can you show code examples ?

```
import FastImage from 'react-native-fast-image'
import DocumentScanner from 'react-native-document-scanner-plugin'

export default () => {
  const [scannedImage, setScannedImage] = useState();

  const scanDocument = async () => {
    const { scannedImages } = await DocumentScanner.scanDocument()
  
    if (scannedImages.length > 0) {
      setScannedImage(scannedImages[0])
    } 

    FastImage.clearMemoryCache() <<< Did you delete the image by adding this line ?

  }

  useEffect(() => {
    scanDocument()
  }, []);

  return (
     <FastImage
        style={{ width: 200, height: 200 }}
        source={{
            uri: scannedImage,
            priority: FastImage.priority.normal,
        }}
        resizeMode={FastImage.resizeMode.contain}
    />
  )
}
```

**Comment by eduardfarkas** [comment]
Hi @silencie,
sorry for the trouble, I definatelly meant to link different library. react-native-fast-image is not meant to handle this.
I am using react-native-file-access

Here is code snippet i use:

```typescript
import { FileSystem } from "react-native-file-access";

const deleteImageFromMemory = (path: string) => {
    FileSystem.exists(path).then((exists) => {
        exists && FileSystem.unlink(path).then((result) => {});
    });
};
