### ISSUE TITLE
Opencv error on Android 12

### ISSUE THREAD

**Issue by himeshparesh93** [WebsiteBeaver/react-native-document-scanner-plugin#58]
No implementation found for long org.opencv.imgcodes.imread_1

Getting this error in Android studio after clicking a photo on Android 12 api 31 only not in Android 10

**Comment by dmarcs** [comment]
I can't reproduce this, but I think it's fixed in 0.7.2

https://github.com/WebsiteBeaver/android-document-scanner/pull/24
load OpenCV in onCreate instead of onResume to avoid OpenCV not being loaded in time
