### ISSUE TITLE
zero-size image when pressing X

### ISSUE THREAD

**Issue by maimistery** [WebsiteBeaver/react-native-document-scanner-plugin#62]
Hi,
![Screenshot_2023-02-09-15-02-05-272-edit_com android camera](https://user-images.githubusercontent.com/20322774/217843135-694e8ef2-8e33-4980-a912-728f233534d8.jpg)

When the user decides to press the X button, it leaves a file in the application directory of size 0, can this behavior be corrected?
as it is in the image:

![Screenshot_2023-02-09-15-38-56-352-edit_com google android documentsui](https://user-images.githubusercontent.com/20322774/217843773-7cfe6683-7e0e-49df-9925-d15120ee4fc9.jpg)

Thanks

**Comment by maimistery** [comment]
i have the last version 0.7.2

**Comment by mwerder** [comment]
Hey, I guess that will need a change inside the package [WebsiteBeaver/android-document-scanner](https://github.com/WebsiteBeaver/android-document-scanner#basic-example) right?

I think we can clean up the file when the camera is canceled. I'd be glad to open a PR

Playing around with the scanner I also noticed that if you scan multiple pages, and then abort, the result will only contain 
`{"status": "cancel"}`
So the file paths of the already scanned pages are never exposed to the react-native application to clean them up.
Wouldn't it make sense to clean up all files after a user cancels the scanner? Or is there a reason to keep them?

**Comment by maimistery** [comment]
Right!

**Comment by dmarcs** [comment]
fixed in [0.7.3](https://github.com/WebsiteBeaver/react-native-document-scanner-plugin/tree/0.7.3)

https://github.com/WebsiteBeaver/android-document-scanner/pull/27

by deleting a photo when the user cancels or retakes
