### ISSUE TITLE
CocoaPods could not find compatible versions

### ISSUE THREAD

**Issue by nemanja3-dev** [WebsiteBeaver/react-native-document-scanner-plugin#64]
I have a problem with CocoaPods after installing package. I have got trough every step and i keeps giving me this error: 
![Screenshot 2023-03-14 at 09 10 34](https://user-images.githubusercontent.com/81969875/224937612-3b339366-4a7f-455d-956c-417b5252a363.jpg)

**Comment by nemanja3-dev** [comment]
I've changed platform :ios to "13.0" in Podfile, and it works, but what if someone is using early versions of iOS?

**Comment by dmarcs** [comment]
It won't work on anything less than 13.
