### ISSUE TITLE
The package 'react-native-document-scanner-plugin' doesn't seem to be linked

### ISSUE THREAD

**Issue by Q8root** [WebsiteBeaver/react-native-document-scanner-plugin#65]
I have tried with both ios and android expo simulator all return the same error 
Android return the following error:-
```
Error: The package 'react-native-document-scanner-plugin' doesn't seem to be linked. Make sure: 

- You rebuilt the app after installing the package
- You are not using Expo managed workflow
```
```
Error: The package 'react-native-document-scanner-plugin' doesn't seem to be linked. Make sure: 

- You have run 'pod install'
- You rebuilt the app after installing the package
- You are not using Expo managed workflow
```

I tried with creating new project using your steps [here ](https://github.com/WebsiteBeaver/react-native-document-scanner-plugin/issues/53#issuecomment-1407139967) got the same errors.

**Comment by dmarcs** [comment]
Try running on a physical device instead of emulator.

**Comment by Q8root** [comment]
https://user-images.githubusercontent.com/33479962/227370239-0453eb58-dcab-499d-9799-a24cca02e1d7.mp4

I tried with my iPhone 14 expo app

**Comment by RowenaRavenclawWithExtraClaws** [comment]
Same problem here.

**Comment by dmarcs** [comment]
This plugin doesn't work with Expo Go. You have to run `npx expo prebuild` in order to make it work with Expo.

**Comment by Q8root** [comment]
> This plugin doesn't work with Expo Go. You have to run `npx expo prebuild` in order to make it work with Expo.

```
q8root@Ahmads-Air my-app % npx expo prebuild
✔ Created native projects | /android, /ios already created | gitignore skipped
✔ Updated package.json and added index.js entry point for iOS and Android
› Installing using yarn
> yarn install
» android: userInterfaceStyle: Install expo-system-ui in your project to enable this feature.
✔ Config synced
✔ Installed pods and initialized Xcode workspace.
q8root@Ahmads-Air my-app % 
```
Getting the same error
Error: The package 'react-native-document-scanner-plugin' doesn't seem to be linked. Make sure: 

- You have run 'pod install'
- You rebuilt the app after installing the package
- You are not using Expo managed workflow

**Comment by dmarcs** [comment]
after npx expo prebuild, how are you running the app?

**Comment by Q8root** [comment]
> after npx expo prebuild, how are you running the app?

First i run the server
`npx expo start`
then scan the qr code from my iPhone 14 camera , click on "open with expo"

**Comment by dmarcs** [comment]
You probably need to run it using `npm run ios`, or by opening xcode and running it

**Comment by Q8root** [comment]
> You probably need to run it using `npm run ios`, or by opening xcode and running it

Worked with me , thank you

**Comment by zabojad** [comment]
> Same problem here. I get this error for iOS:
> 
> ```
> [!] CocoaPods could not find compatible versions for pod "react-native-document-scanner-plugin"
> dependency was found, but they required a higher minimum deployment target.
> ```
> 
> Just replace the line `platform :ios, min_ios_version_supported` with `platform :ios, 13` in the Podfile.

This is what worked for me... (RN 0.72 project)

**Comment by ijomah** [comment]
Hello @dmarcs , thanks for the scanner.
Please I have a few issues.
I have built  a single component app with the scanner and install on my devices (Android) and it worked. Now if add it to my medium sized app and navigate to the scanner, it doesn't trigger the scanner.
I have tried this with expo router and react navigation libraries, no solution yet. I have simply my code, yet not working 
What am I missing?
Are there some tips you can give?

**Comment by rperezPMC** [comment]
> You probably need to run it using `npm run ios`, or by opening xcode and running it

I'm getting the same error as everyone else, but I'm using Android. I guess I have to run `npm run android`?
