### ISSUE TITLE
Error: The operation couldn’t be completed. (AVFoundationErrorDomain error -11800.)

### ISSUE THREAD

**Issue by PhamChuongBD** [WebsiteBeaver/react-native-document-scanner-plugin#73]
Hello ,
After calling the event DocumentScanner.scanDocument(), if I cancel it, the app will encounter an error: Error: The operation couldn't be completed. (AVFoundationErrorDomain error -11800.). Is there any way to solve this issue? Thank you.

**Comment by dmarcs** [comment]
Error code 11800 is an unknown error https://developer.apple.com/documentation/avfoundation/averror/code/unknown. When I cancel a scan it doesn't throw an error.

**Comment by PhamChuongBD** [comment]
```
Environment:
info Fetching system and libraries information...
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M2
    Memory: 155.34 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.9862592
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.7 => 0.71.7 
```
<img width="1218" alt="Screenshot 2023-05-08 at 09 28 53" src="https://user-images.githubusercontent.com/11403038/236720581-b219d375-e15a-488a-a2b1-1a1d75f020dc.png">

**Comment by dmarcs** [comment]
Can you try to create a new react native project, install this plugin, and see if this happens? I want to rule out the possibility that another plugin is causing this.

**Comment by PhamChuongBD** [comment]
Oke I have tried it and it works fine, perhaps the issue is due to some libraries that are not compatible with each other.
Thanks for the help .
