### ISSUE TITLE
Unable to make apk for my project

### ISSUE THREAD

**Issue by ashishonmobile** [WebsiteBeaver/react-native-document-scanner-plugin#84]
Execution failed for task ':react-native-document-scanner-plugin:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR: <directory>/node_modules/react-native-document-scanner-plugin/android/build/intermediates/merged_res/release/values/values.xml:2753: AAPT: error: resource android:attr/lStar not found.

any solution for this.

**Comment by dmarcs** [comment]
You might need to change the build.gradle versions to match https://github.com/WebsiteBeaver/react-native-document-scanner-plugin/blob/master/example/android/build.gradle
