### ISSUE TITLE
Task :react-native-document-scanner-plugin:verifyReleaseResources FAILED

### ISSUE THREAD

**Issue by krunal-sisnolabs** [WebsiteBeaver/react-native-document-scanner-plugin#86]
When I build app for release I got this error.

Error details:

> Task :react-native-document-scanner-plugin:verifyReleaseResources FAILED
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-document-scanner-plugin:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/var/www/html/1kunal/banking/loankatta/node_modules/react-native-document-scanner-plugin/android/build/intermediates/merged_res/release/values/values.xml:2753: AAPT: error: resource android:attr/lStar not found.
         

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 3 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.

**Comment by dmarcs** [comment]
Try changing the compileSdk and targetSdk to 30
