### ISSUE TITLE
Android build failed

### ISSUE THREAD

**Issue by basit78** [WebsiteBeaver/react-native-document-scanner-plugin#87]
I am using react native latest version it properly working but when i create a android build it return error 

> Task :react-native-document-scanner-plugin:verifyReleaseResources FAILED
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-document-scanner-plugin:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/Users/alogace/Documents/projects/react-native-projects/nova-food-mobile/node_modules/react-native-document-scanner-plugin/android/build/intermediates/merged_res/release/values/values.xml:2753: AAPT: error: resource android:attr/lStar not found.

**Comment by dmarcs** [comment]
Try changing the compileSdk and targetSdk to 30

**Comment by basit78** [comment]
still error

**Comment by dmarcs** [comment]
Please try with version 0.80 of this plugin. If that doesn't work either run the example in this repo, or create a new React Native project and only install this plugin.

**Comment by ddikodroid** [comment]
> AAPT: error: resource android:attr/lStar not found.

maybe you can try solution from https://github.com/mixpanel/mixpanel-react-native/issues/164#issuecomment-1260920066

**Comment by c-info** [comment]
Having same issue after upgrading plugin

**Comment by barbhackk** [comment]
Hi,

For me with the latest version of React, I use compileSdkVersion = 33 and targetSdkVersion = 33 but in build.gradle from document-scanner-plugin at "android/build.gradle" is 

```
compileSdkVersion safeExtGet('DocumentScanner_compileSdkVersion', 30)
    defaultConfig {
        minSdkVersion safeExtGet('DocumentScanner_minSdkVersion', 16)
        targetSdkVersion safeExtGet('DocumentScanner_targetSdkVersion', 30)
        versionCode 1
        versionName "1.0"

    }
```

Change 30 to 33 (or 31 according to your project) and works for me with ```./gradlew assembleRelease``` without ```app:```

I think the function ```safeExtGet(prop, fallback)``` should return the version of the root project.

Seb

**Comment by barbhackk** [comment]
For information : [https://support.google.com/googleplay/android-developer/thread/207230488/new-deadline-target-api-level?hl=en#:~:text=Starting%20August%2031%2C%202023%3A,all%20users%20on%20Google%20Play.](https://support.google.com/googleplay/android-developer/thread/207230488/new-deadline-target-api-level?hl=en#:~:text=Starting%20August%2031%2C%202023%3A,all%20users%20on%20Google%20Play.)

**Comment by dmarcs** [comment]
I updated to compileSdk and targetSdk 33 in https://github.com/WebsiteBeaver/react-native-document-scanner-plugin/pull/95

If anyone still gets this error it's likely because compileSdk and targetSdk need to be changed. I would create a new React Native project, install this plugin, and see if you still get an error.
