### ISSUE TITLE
fail to build the app on Android after install the package

### ISSUE THREAD

**Issue by DAHUO-Melbourne** [WebsiteBeaver/react-native-document-scanner-plugin#88]
I goe this message after I installed the package and run the app:

error Failed to install the app. Command failed with exit code 1: gradlew.bat tasks FAILURE: Build failed with an exception. * What went wrong: Execution failed for task ':tasks'. > Could not create task ':react-native-document-scanner-plugin:compileDebugJavaWithJavac'. > In order to compile Java 9+ source, please set compileSdkVersion to 30 or above * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. * Get more help at https://help.gradle.org/ BUILD FAILED in 21s
Starting a Gradle Daemon, 4 busy and 2 incompatible and 2 stopped Daemons could not be reused, use --status for details > Task :gradle-plugin:compileKotlin UP-TO-DATE > Task :gradle-plugin:compileJava NO-SOURCE > Task :gradle-plugin:pluginDescriptors UP-TO-DATE > Task :gradle-plugin:processResources UP-TO-DATE > Task :gradle-plugin:classes UP-TO-DATE > Task :gradle-plugin:jar UP-TO-DATE > Task :gradle-plugin:inspectClassesForKotlinIC UP-TO-DATE > Task :tasks FAILED Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0. You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins. See https://docs.gradle.org/8.0.1/userguide/command_line_interface.html#sec:command_line_warnings 6 actionable tasks: 1 executed, 5 up-to-date.

I run: 
npm install react-native-document-scanner-plugin
then
npm run android

and then it failed. The messages r shown above.

Is there any one knows how to solve it？

**Comment by dmarcs** [comment]
Can you try using a previous version of gradle?

**Comment by DAHUO-Melbourne** [comment]
sorry man, could u tell me the correct version of gradle and how could I degrade the gradle? What command could I run? Because I'm a fresh man in RN, don't have too much exp, thank u very much!

**Comment by dmarcs** [comment]
Try 6.2. You don't need to run a command. Open Android Studio, and change the settings to lower the gradle version.

**Comment by dmarcs** [comment]
This should be fixed in 0.80 by https://github.com/WebsiteBeaver/react-native-document-scanner-plugin/commit/3d9197964d5aaa73ecafd0df54097cd812e800c9 - update target and compile sdk versions to 30

**Comment by auguyon** [comment]
Hello, got the same error after upgrading the lib.

"react-native": "0.72.3",
"react-native-document-scanner-plugin": "^0.7.4",
