### ISSUE TITLE
Not working on expo with development build or EAS build

### ISSUE THREAD

**Issue by silencie** [WebsiteBeaver/react-native-document-scanner-plugin#9]
I would like to try this library with my Expo(managed workflow) project but it's not working. Can I use the library in Expo ?

**npx expo run:ios**

<img width="828" alt="Screen Shot 2565-10-11 at 16 46 50" src="https://user-images.githubusercontent.com/115603511/195240304-51464413-1fbe-4f85-8b83-be01b5548a09.png">

**eas build --profile preview --platform ios**

<img width="1200" alt="Screen Shot 2565-10-11 at 17 46 37" src="https://user-images.githubusercontent.com/115603511/195240342-17413cca-c05c-4c66-8c36-251d496259e3.png">

**Comment by JoaoScheleder** [comment]
Try this, it worked for me, probably you'll face the same error as me after that.  
useEffect(() => {
    // call scanDocument on load
    scanDocument()
      .then(data => console.log(data))
      .catch(error => console.log(error))
      
  }, []);

**Comment by dmarcs** [comment]
expo isn't supported as of now

**Comment by dmarcs** [comment]
fixed in https://github.com/WebsiteBeaver/react-native-document-scanner-plugin/pull/18 by adding expo plugin config
