### ISSUE TITLE
ANDROID BUILD FAILED

### ISSUE THREAD

**Issue by ronuelbmoralita** [WebsiteBeaver/react-native-document-scanner-plugin#90]
Hello Sir, Is there any solution now to this Error?

BUILD FAILED in 8s
error Failed to install the app. Command failed with exit code 1: gradlew.bat tasks FAILURE: Build failed with an exception. * What went wrong: Execution failed for task ':tasks'. > Could not create task ':react-native-document-scanner-plugin:compileDebugJavaWithJavac'. > In order to compile Java 9+ source, please set compileSdkVersion to 30 or above * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. * Get more help at https://help.gradle.org BUILD FAILED in 8s

**Comment by dmarcs** [comment]
try to set compileSdkVersion to 30

**Comment by ronuelbmoralita** [comment]
Sir, thanks for the reply! Unfortunately, I have tried this but it doesn't work.

**Comment by ronuelbmoralita** [comment]
> try to set compileSdkVersion to 30

Sir, thanks for the reply! Unfortunately, I have tried this but it doesn't work.

**Comment by ronuelbmoralita** [comment]
My guess is the conflict between your library and the react native version 0.72 I'm using.

**Comment by ronuelbmoralita** [comment]
Any update Sir?

**Comment by dmarcs** [comment]
I would try to start a new React Native project using 0.72, install only this plugin, and see if it works.

**Comment by ronuelbmoralita** [comment]
Thank you, Sir. You know I'm struggling right now and I want to make my own startup but I don't have enough budget. My previous employer's salary did not provide enough room for savings. I'm relying on some open-source API because Google's service is too expensive.

**Comment by omercandemir** [comment]
Same problem, React Native was running on version 71.11 but I am getting the same error on version 72.1.

**Comment by ronuelbmoralita** [comment]
> Same problem, React Native was running on version 71.11 but I am getting the same error on version 72.1.

I think we should wait for Sir David for the next release.

**Comment by dmarcs** [comment]
This should be fixed in 0.80 by https://github.com/WebsiteBeaver/react-native-document-scanner-plugin/commit/3d9197964d5aaa73ecafd0df54097cd812e800c9 - update target and compile sdk versions to 30

**Comment by ronuelbmoralita** [comment]
Sir, What if other dependencies of my projects also need to use target and compile versions of sdk 33. Will your library work with target and compile versions of sdk 33? I'm using the latest version of react native and libraries.
