### ISSUE TITLE
Document cropper background is white on IOS

### ISSUE THREAD

**Issue by krrud** [WebsiteBeaver/react-native-document-scanner-plugin#94]
Wonderful plugin!

I 've run into a small issue on IOS where the background above and below the cropping area on IOS is white instead of black.
![documentCrop](https://github.com/WebsiteBeaver/react-native-document-scanner-plugin/assets/1253057/caca0972-1f8f-4dad-98bc-8344035a42a3)

Is it possible to tweak the colors?

**Comment by dmarcs** [comment]
Try changing your phone settings to use dark mode.
