### ISSUE TITLE
The package 'react-native-document-scanner-plugin' doesn't seem to be linked.

### ISSUE THREAD

**Issue by shahidavalisyed** [WebsiteBeaver/react-native-document-scanner-plugin#97]
Possible Unhandled Promise Rejection (id: 1):
Error: The package 'react-native-document-scanner-plugin' doesn't seem to be linked. Make sure:
- You rebuilt the app after installing the package - You are not using Expo managed workflow
Error: The package 'react-native-document-scanner-plugin' doesn't seem to be linked. Make sure:

**Comment by dmarcs** [comment]
Make sure that you follow these steps https://github.com/WebsiteBeaver/react-native-document-scanner-plugin#expo to run your app, and that you're using a physical device.
